### ISSUE TITLE
CLI access to dtscalibration

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#195]
It could be nice to be able to run the calibration routines using a command line interface.

The calibration configuration could be specified in a yaml configuration file, for example:

```yaml
name: "test_setup"
calibration-configuration:
    mode: "double-ended"
    align_channels: true
    sections:
        warm_bath:
            sensor: "Pt100_1"
            start: 10.50
            end: 21.15
        cold_bath:
            sensor: "Pt100_2"
            start: 25.60
            end: 35.45
```
